In [3]:
import numpy as np #import Libraries

## Creating Arrays

In [5]:
np.array(np.arange(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
mylist = [1,2,4,6]


In [7]:
a=np.array(mylist)

In [8]:
a

array([1, 2, 4, 6])

In [9]:
t=np.array([[1,2,3,4],[9,0,3,6]])

In [10]:
t

array([[1, 2, 3, 4],
       [9, 0, 3, 6]])

In [12]:
np.zeros(5) #with zeros

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [17]:
np. ones(5) #with ones

array([ 1.,  1.,  1.,  1.,  1.])

In [18]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [19]:
np.arange(10,20,)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.linspace(10,100,10) #it gives n elements(x,y,n)

array([  10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,   90.,  100.])

In [21]:
np.linspace(1,10,100)

array([  1.        ,   1.09090909,   1.18181818,   1.27272727,
         1.36363636,   1.45454545,   1.54545455,   1.63636364,
         1.72727273,   1.81818182,   1.90909091,   2.        ,
         2.09090909,   2.18181818,   2.27272727,   2.36363636,
         2.45454545,   2.54545455,   2.63636364,   2.72727273,
         2.81818182,   2.90909091,   3.        ,   3.09090909,
         3.18181818,   3.27272727,   3.36363636,   3.45454545,
         3.54545455,   3.63636364,   3.72727273,   3.81818182,
         3.90909091,   4.        ,   4.09090909,   4.18181818,
         4.27272727,   4.36363636,   4.45454545,   4.54545455,
         4.63636364,   4.72727273,   4.81818182,   4.90909091,
         5.        ,   5.09090909,   5.18181818,   5.27272727,
         5.36363636,   5.45454545,   5.54545455,   5.63636364,
         5.72727273,   5.81818182,   5.90909091,   6.        ,
         6.09090909,   6.18181818,   6.27272727,   6.36363636,
         6.45454545,   6.54545455,   6.63636364,   6.72

In [22]:
np.eye(5) #Identity matrix

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [23]:
np.random.rand(11) #generating random numebres in arrays

array([ 0.71103257,  0.88305656,  0.91012779,  0.41578623,  0.63375538,
        0.87971474,  0.13980837,  0.74152487,  0.65626983,  0.35413928,
        0.63722021])

In [24]:
np.random.rand(5,5)

array([[ 0.94808705,  0.33889508,  0.31267845,  0.8516817 ,  0.38899032],
       [ 0.17778741,  0.64558691,  0.48375415,  0.74274997,  0.38489807],
       [ 0.13220803,  0.03540225,  0.00975824,  0.46097907,  0.81120198],
       [ 0.52880965,  0.47352956,  0.2749922 ,  0.98830279,  0.3052337 ],
       [ 0.92645196,  0.37765274,  0.6445784 ,  0.6678131 ,  0.63369231]])

In [25]:
np.random.randn(10) # generate random numbers in arrays in normal distribution

array([ 0.70804799,  1.05102648, -0.48693931,  0.68945227, -0.02430076,
        1.09029356, -1.26385306, -0.05561587, -2.06908971, -0.1944921 ])

In [28]:
np.random.randn(5,4)

array([[ 1.58838461, -0.55455441, -0.80542306, -1.14237813],
       [-0.85694719,  1.04519022,  0.51369865, -0.73197403],
       [-1.76265366,  1.09800972, -1.15983523,  0.06533191],
       [ 0.09945404,  0.7059567 ,  0.00473824,  1.96634389],
       [ 0.53551191,  0.65139639,  0.02512245,  0.95725397]])

In [29]:
np.random.randint(10) # generates a single random integer

6

In [30]:
np.random.randint(10,100) #in between x and y

22

In [31]:
np.random.randint(10,20,20) # it generates n numbers in x and y.

array([14, 10, 12, 19, 14, 15, 14, 13, 16, 15, 10, 11, 12, 15, 10, 15, 16,
       12, 19, 17])

In [32]:
np.random.randint(9999,99999,5)

array([41073, 97060, 23908, 56484, 34190])

In [35]:
arr = np.random.rand(20)

In [36]:
arr

array([ 0.75396376,  0.57093706,  0.95691003,  0.45687289,  0.1786206 ,
        0.04722663,  0.41047061,  0.41984143,  0.91841814,  0.47732899,
        0.81504902,  0.23527116,  0.49887767,  0.18467724,  0.39413842,
        0.07002748,  0.17856411,  0.61151992,  0.77665843,  0.76640187])

In [37]:
arr.reshape(4,5) # reshaping arrays

array([[ 0.75396376,  0.57093706,  0.95691003,  0.45687289,  0.1786206 ],
       [ 0.04722663,  0.41047061,  0.41984143,  0.91841814,  0.47732899],
       [ 0.81504902,  0.23527116,  0.49887767,  0.18467724,  0.39413842],
       [ 0.07002748,  0.17856411,  0.61151992,  0.77665843,  0.76640187]])

In [38]:
arr = np.arange(25)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr = arr.reshape(5,5)

In [41]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
arr.min() # array of min

0

In [43]:
arr.max() # array of max

24

In [44]:
arr.argmax()

24

In [45]:
arr.argmin()

0

In [50]:
arr.dtype # datatype of array

dtype('int32')

In [51]:
arr.shape # shape of array

(5, 5)