In [1]:
import numpy as np

In [2]:
arr = np.arange(100,999,25)

In [3]:
arr

array([100, 125, 150, 175, 200, 225, 250, 275, 300, 325, 350, 375, 400,
       425, 450, 475, 500, 525, 550, 575, 600, 625, 650, 675, 700, 725,
       750, 775, 800, 825, 850, 875, 900, 925, 950, 975])

In [5]:
arr = arr.reshape(6,6)

In [6]:
arr

array([[100, 125, 150, 175, 200, 225],
       [250, 275, 300, 325, 350, 375],
       [400, 425, 450, 475, 500, 525],
       [550, 575, 600, 625, 650, 675],
       [700, 725, 750, 775, 800, 825],
       [850, 875, 900, 925, 950, 975]])

In [7]:
arr[0]

array([100, 125, 150, 175, 200, 225])

In [8]:
arr[0,1]

125

In [9]:
arr[0,0]

100

In [10]:
arr[0][1]

125

In [11]:
arr[0:,1]

array([125, 275, 425, 575, 725, 875])

In [12]:
arr[-1]

array([850, 875, 900, 925, 950, 975])

In [13]:
arr

array([[100, 125, 150, 175, 200, 225],
       [250, 275, 300, 325, 350, 375],
       [400, 425, 450, 475, 500, 525],
       [550, 575, 600, 625, 650, 675],
       [700, 725, 750, 775, 800, 825],
       [850, 875, 900, 925, 950, 975]])

In [14]:
arr[3,2]

600

In [15]:
arr[5,5]

975

In [17]:
arr[0:,5]

array([225, 375, 525, 675, 825, 975])

## slice and assign

In [31]:
ab = arr[3:,:3]

In [32]:
ab #it is a reference of array

array([[550, 575, 600],
       [700, 725, 750],
       [850, 875, 900]])

In [36]:
ab[0]=99

In [37]:
ab # it will changed 0th row in both original and reference 

array([[ 99,  99,  99],
       [700, 725, 750],
       [850, 875, 900]])

In [38]:
arr

array([[100, 125, 150, 175, 200, 225],
       [250, 275, 300, 325, 350, 375],
       [400, 425, 450, 475, 500, 525],
       [ 99,  99,  99, 625, 650, 675],
       [700, 725, 750, 775, 800, 825],
       [850, 875, 900, 925, 950, 975]])

In [ ]:
# copying the array to made changes..

In [33]:
arr_copy=ab.copy()

In [35]:
arr_copy

array([[550, 575, 600],
       [700, 725, 750],
       [850, 875, 900]])

In [39]:
arr_copy >10

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [40]:
arr_copy >1000

array([[False, False, False],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [41]:
arr_copy[arr_copy>500]

array([550, 575, 600, 700, 725, 750, 850, 875, 900])

In [42]:
arr

array([[100, 125, 150, 175, 200, 225],
       [250, 275, 300, 325, 350, 375],
       [400, 425, 450, 475, 500, 525],
       [ 99,  99,  99, 625, 650, 675],
       [700, 725, 750, 775, 800, 825],
       [850, 875, 900, 925, 950, 975]])

In [43]:
arr[0:2,:2]

array([[100, 125],
       [250, 275]])

In [44]:
arr[3:5,3]

array([625, 775])