In [1]:
import numpy as np

In [2]:
arr = np.arange(10,40,5)

In [3]:
arr

array([10, 15, 20, 25, 30, 35])

In [4]:
abc = arr +arr

In [5]:
abc

array([20, 30, 40, 50, 60, 70])

In [6]:
ap = arr -abc

In [7]:
ap

array([-10, -15, -20, -25, -30, -35])

In [8]:
apv = ap*abc

In [9]:
apv

array([ -200,  -450,  -800, -1250, -1800, -2450])

In [11]:
abc +20

array([40, 50, 60, 70, 80, 90])

In [12]:
abc -2

array([18, 28, 38, 48, 58, 68])

In [13]:
abc *4

array([ 80, 120, 160, 200, 240, 280])

In [14]:
abc /4

array([  5. ,   7.5,  10. ,  12.5,  15. ,  17.5])

In [15]:
abc # its not effected because we are not assigned

array([20, 30, 40, 50, 60, 70])

In [16]:
abc.max()

70

In [17]:
abc.min()

20

In [18]:
np.sin(abc)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485, -0.30481062,
        0.77389068])

In [19]:
np.abs(-10)

10

In [20]:
np.absolute(20.89)

20.890000000000001

In [21]:
np.add(10,10)

20

In [22]:
np.all(10)

True

In [23]:
np.all(-1)

True